/**
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
Example 3:

Input: s = "a", t = "aa"
Output: "a"
*/
class Solution {
public:
    char findTheDifference(string s, string t) {
        unordered_map<char,int>m;
        for(auto i:t)
            m[i]++;
        for(auto i:s)
            m[i]--;
        char h;
        for(auto i:m)
        {
            if(i.second==1)
            {
               h=i.first;
                break;
            }
        }
        return h;
    }
};
